parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: vivalapizza
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 6d6eba50429981739882832fb10de6f87
    database_path: null
